---
name: optimize_pat_lookup
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/217620
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/work_items/590498
milestone: '18.10'
type: gitlab_com_derisk
group: group::authentication
default_enabled: false
